config/routes.rb
Applify::Application.routes.draw do
  devise_for :users
  resources :job_infos
  resources :job_applications

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  root 'job_infos#index'

end

app/models/job_application.rb
class JobApplication < ActiveRecord::Base

  belongs_to :user

end

app/models/job_info.rb
class JobInfo < ActiveRecord::Base
  belongs_to :user

  CONTACTS = ['Home Phone', 'Cell Phone', 'Work Phone']
  AUTHS = ["Green Card Holder", "Canadian Citizen", "U.S. Citizen", "TN Permit Holder", "Employment Authorization Document", "Have H-1 Visa", "Need H-1 Visa"]
  validates :first_name, presence: true, format: { with: /\w[a-z]+\z/i }
  validates :last_name, presence: true, format: { with: /\w[a-z]+\z/i }
  validates :dice_email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }
  validates :dice_password, presence: true
  validates :desired_position, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true, format: {:with => /^\d{5}(-\d{4})?$/,
                                                :message => "should be in the form 12345 or 12345-1234", multiline: true}
  validates :resume, presence: true
  validates :home_phone, presence: true
  validates :primary_contact, presence: true , inclusion: { in: CONTACTS }
  validates :title, presence: true
  validates :daily_schedule, default: false
  validates :work_auth, presence: true, inclusion: { in: AUTHS }
  validates :skills, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :job_infos
  has_many :job_applications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @job_applications = current_user.job_applications
    
  end

end

app/controllers/job_infos_controller.rb
class JobInfosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_job_info, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  def index

    @job_infos = @user.job_infos
  end

  def new
    @job_info = JobInfo.new
  end

  def create
    @job_info = JobInfo.new(job_info_params)
    @job_info.user = current_user
    @job_info.skills = @job_info.skills.split(' ').shift(20).join(' ')
    if @job_info.save
      DiceWorker.perform_async(@job_info.id)
      DiceJobWorker.perform_async
      MonsterWorker.perform_async
      redirect_to job_infos_path(@job_info),
        notice: 'Job Info Added'
    else
      render :new
    end
  end

  def show
  end

  def edit
    @job_info.skills = @job_info.skills.split(' ').shift(20).join(' ')

    if @job_info.save
      DiceWorker.perform_async(@job_info.id)
      redirect_to job_infos_path(@job_info),
        notice: 'Job Info Added'
    else
      render :new
    end
  end

  def update
    if @job_info.update(job_info_params)
      redirect_to job_infos_path(@job_info),
       notice: 'Updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @job_info.destroy
    redirect_to job_infos_url,
      notice: 'Deleted successfully'
  end

  private
  def set_job_info
    @job_info = JobInfo.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def job_info_params
    params.require(:job_info).permit(:primary_contact, :current_salary, :desired_salary, :cell_phone, :work_phone, :home_phone, :cover_letter,
                                      :resume, :zip_code, :state, :city, :address, :dice_email, :dice_password, :desired_position, :last_name, :first_name, :title, :daily_schedule,
                                      :filepicker_url, :work_auth, :skills)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/job_applications/index.html.erb
<h1> List of Job Applications </h1>

<%= link_to "Home", job_infos_path %>

<ul>
  <li><% @job_applications.each do |app| %></li>
  <li><%= link_to app.job_title, job_applications_path(app) %></li>
  <%= link_to 'Display', app %> |
  <%= link_to 'Edit', edit_job_application_path(app) %> |
  <%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Do You Want To Delete This Application Information?' } %>
  <li><% end %></li>
</ul>

<script type='text/javascript' src='jsapi'></script>
<script type='text/javascript'>
  google.load('visualization', '1', {'packages':['annotatedtimeline']});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = new google.visualization.DataTable();
    data.addColumn('datetime', 'Date');
    data.addColumn('number', 'Happiness');   
    data.addColumn('number', 'Image Analysis');
    data.addColumn('string', 'Post');

    var date = gon.date;
    var happiness_log = gon.happiness_logs;
    happiness_log.forEach( function (arrayItem) {
      for (var i in date) {
        data.addRows([
         [new Date(Date.parse(date[i])), arrayItem['happy_scale'], arrayItem['smile'], arrayItem['main_post']]
         ]);
      }
    });

    var options = {
      colors: ['#e0440e', '#FFCC00'],
      displayAnnotations: true,
      max: 10,
      fill: 10,
      wmode: 'opaque',
      thickness: 2,
      displayAnnotations: true,
    };

    var chart = new google.visualization.AnnotatedTimeLine(document.getElementById('chart_div'));

    chart.draw(data, options);
  }
</script>

app/views/job_infos/_job_infos.html.erb
<%= simple_form_for(@job_info) do |f| %>

  <%= f.input :title, label: 'Profile Name' %>
  <%= f.input :desired_position %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :dice_email %>
  <%= f.input :dice_password %>
  <%= f.input :address %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.input :zip_code %>
  <%= f.input :resume, input_html: {rows: 15} %> or
  <%= f.filepicker_field :filepicker_url, services: "COMPUTER, URL", value: "Upload Resume", button_text: 'Upload Resume' %>
  <%= f.input :cover_letter, input_html: {rows: 15}%>
  <%= f.input :home_phone %>
  <%= f.input :work_phone %>
  <%= f.input :cell_phone %>
  <%= f.input :primary_contact, collection: ['Home Phone', 'Cell Phone', 'Work Phone'] %>
  <%= f.input :skills, label: 'Enter Skills (Limit: 20)' %>
  <%= f.input :desired_salary %>
  <%= f.input :current_salary %>
  <%= f.input :work_auth, collection: ["Green Card Holder", "Canadian Citizen",
     "U.S. Citizen", "TN Permit Holder", "Employment Authorization Document",
     "Have H-1 Visa", "Need H-1 Visa"] %>
  <%= f.input :daily_schedule, label: "Check to Schedule Daily Submission of Resume" %>
  <%= f.button :submit, 'Store Job Info' %>

<% end %>
<%= filepicker_js_include_tag %>

app/views/job_infos/edit.html.erb
<h2> Edit Job Information </h2>
<%= render 'job_infos/job_infos' %>

app/views/job_infos/index.html.erb
<h1> List of Job Information </h1>

<div class = "large-12 medium-12 columns">
  <%= link_to "Enter Job Info", new_job_info_path, class: "medium button"%>
</div>
<%= link_to 'See Job Applications', job_applications_path %>
<ul>
  <li><% @job_infos.each do |job| %></li>
  <li><%= link_to job.title, job_infos_path(job) %></li>
  <%= link_to 'Display', job %> |
  <%= link_to 'Edit', edit_job_info_path(job) %> |
  <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Do You Want To Delete This Information?' } %>
  <li><% end %></li>
</ul>

app/views/job_infos/new.html.erb
<h2> Add Job Information For Applications </h2>

<%= render 'job_infos/job_infos' %>

<%= link_to 'Back', job_infos_path %>

app/views/job_infos/show.html.erb
<table>
  <tr>
    <p><%= @job_info.title %></p>
    <% unless @job_info.filepicker_url == "Add Image" || @job_info.filepicker_url.blank? %>
      <%= filepicker_image_tag @job_info.filepicker_url, w: 400, h: 400, fit: 'clip', class: 'center' %>
      <%= filepicker_save_button "Save", @job_info.filepicker_url, "image/jpg" %>
    <% end %>
    <td><%= link_to "Edit", edit_job_info_path(@job_info) %></td>
    <td><%= link_to "Delete", job_info_path(@job_info),
      method: :delete %></td>
  </tr>
</table>

<p><%= link_to 'Home', job_infos_path %></p>

app/views/layouts/_navbar.html.erb
<div class="sticky">
  <nav class="top-bar" data-topbar>

    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Appify - Sending Out Applications For You!</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <% if user_signed_in? %>
          <li class="active"><%= current_user.email %></li>
          <li class="active"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li class="active"><%= link_to "Sign Up", new_user_registration_path%></li>
          <li class="active"><%= link_to "Sign In", new_user_session_path %></li>
        <%end%>
      </ul>
              
      <span class="has-form">

      </span>
    </section>

  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appify</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>